I am commiting all the answers to all the quizzes of the challenge
DomanskaGrzyb/awesome-google-mobile-web-challenge-links-2017 pull request #107
Opened 2018-02-06 10:05 UTC by luuizpaulo

Hey! 

I have done two commits: The first one I have written a bad commit message as '_modified main readme file_', but what I meant was '_added myself in the contributors list_' (sorry I just realized now how bad my message was). The second commit was the add of all the answers of all the quizzes. 

I have used Prettier in all the files, so the code format should be good.

That is it, let me know if I made some mistake. =) Have a nice day!

2018-02-13 16:34 UTC, Agheb requested changes

2018-02-13 16:34 UTC, Agheb commented on README.md
> +* [Luiz Carneiro](https://github.com/luuizpaulo)
Add link in the content section to navigate from there

2018-02-13 16:34 UTC, Agheb commented on challenge-quizzes/built_ins/exercise8_15/readme.md
> +```script.js
[optional] introductory text can directly be written in Markdown rather than comments in a codeblock.

2018-02-13 16:34 UTC, Agheb commented on challenge-quizzes/readme.md
> +## Message to contributors:
this sentence can be added to the contributor guidelines

2018-02-13 16:34 UTC, Agheb commented on challenge-quizzes/readme.md
> +## License
The repo already contains license information. You can remove this section.

2018-02-13 16:40 UTC, Agheb commented
Thanks, @luuizpaulo for your first contribution. Please look into the changes I've requested, and we're good to go.

2019-10-13 18:44 UTC, miguelbayon commented on challenge-quizzes/built_ins/exercise8_15/readme.md
> +// I am a little bit confused - why would I need to do this?
Test

2022-04-23 10:21 UTC, merged